Revert "common/io_exerciser: Add version argument to callbacks in ceph_radios_io_sequence"
This reverts commit 5b90117348d030db16738ae06e9308ade4355bb0. This
avoids a compile error in the build:
```
/19.3.0-5425-g27af63b2/rpm/el9/BUILD/ceph-19.3.0-5425-g27af63b2/src/common/io_exerciser/RadosIo.cc:1:
/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos9/DIST/centos9/MACHINE_SIZE/gigantic/release/19.3.0-5425-g27af63b2/rpm/el9/BUILD/ceph-19.3.0-5425-g27af63b2/src/common/io_exerciser/RadosIo.cc: In member function ‘virtual bool ceph::io_exerciser::RadosIo::readyForIoOp(ceph::io_exerciser::IoOp&)’:
/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos9/DIST/centos9/MACHINE_SIZE/gigantic/release/19.3.0-5425-g27af63b2/rpm/el9/BUILD/ceph-19.3.0-5425-g27af63b2/src/common/io_exerciser/RadosIo.cc:84:20: error: ‘ceph::mutex’ {aka ‘class std::mutex’} has no member named ‘is_locked_by_me’
```

Signed-off-by: Laura Flores <lflores@ibm.com>